defaults:
    - _self_
    - general : general_default
    - model : discrete
    - train : train_default
    - dataset : qm9

hydra:
  job:
    chdir: True
  run:
    dir: /home/du4/19CS30053/MTP2/DiGress/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}




